add relative sizes to OP
argyleink/open-props pull request #370
Opened 2023-05-08 18:51 UTC by PaoloGiraudi

Fixes #336

2023-05-30 16:23 UTC, argyleink requested changes
thank you for this! 🙏🏻  
not sure how it skipped my radar, i try and stay on these PRs. 

i've left a few comments, nothing critical.

the one thing i'm unsure of, is if these should ship in the main bundle or as an optional import? have thoughts on this? my first thought was to ship as an additional import, but then again, the colors alone are what really bloat the package not the sizes, and in a future release i'll be heavily cutting back the colors shipped. so I dunno! i'm on the fence.

2023-05-30 16:23 UTC, argyleink commented on docsite/index.html
> +          <h5>Relative Sizes</h5>
this title is the same as the regular sizes, which makes me think the regular sizes title should change to either "Document Relative Sizes" or just "Sizes".

2023-05-30 16:23 UTC, argyleink commented on docsite/index.css
> +    background-size: var(--size-relative-15) var(--size-relative-12);
thanks for dogfooding / backporting these length updates!

2023-05-30 16:23 UTC, argyleink commented on docsite/index.html
> +          <h5>Usage Sample</h5>
be cool if this demo area had a "font size picker" select element so you could see the sizes adapt to a given font size. really help set the feature in. thoughts? it'd be kinda like how line-height and font-size have on.

2023-05-30 16:23 UTC, argyleink commented on src/props.sizes.js
> +  '--size-relative-15': '12ch',
I wonder if this list should be the exact same as the rem sizes but just swapped to the `ch` unit? it'd make interchanging between them easier AND the mental model of the scale easier. We'd also gain the 2 negative values. So like, less to manage and more consistent? thoughts?

2023-06-02 11:25 UTC, PaoloGiraudi commented
@argyleink A couple notes: 
 - In my opinion, these variables should be part of the main bundle. Having `ch` and `rem` units by default will give users a great toolkit to build UI. 
 - By using the same values as for `rem`, we don't have [this specific size](https://github.com/argyleink/open-props/pull/370/files#diff-c46b9c0fde3e24499651d4726fdf2b5368926cd9e62196c9f3976dca73b9c4e9R48) used in `buttons`.

2023-06-14 21:36 UTC, argyleink commented on docsite/index.css
> +    background-size: var(--size-relative-13) var(--size-relative-11);
not exactly the same, but still works 👍🏻

2023-06-14 21:42 UTC, argyleink approved these changes
rad work!

2023-06-14 21:43 UTC, argyleink commented on docsite/index.html
> +          <h5>Usage Sample</h5>
you did perfect 👍🏻

2023-06-14 21:46 UTC, merged

2023-06-14 21:57 UTC, argyleink commented
available in v1.5.9 🎉